# Generated by Django 3.0.6 on 2020-06-24 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasaction',
            name='expect_received_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='วันที่คาดกว่าจะได้'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trasaction',
            name='expect_sending_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='วันที่คาดว่าจะส่งของ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trasaction',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='วันที่รับของ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trasaction',
            name='sending_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='วันที่ส่งของ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trasaction',
            name='purchase_date',
            field=models.DateTimeField(help_text='วันสั่งซื้อ'),
        ),
    ]
