# Generated by Django 3.0.6 on 2020-06-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20200624_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Purchase',
        ),
        migrations.RenameModel(
            old_name='TransactionStatus',
            new_name='PurchaseStatus',
        ),
    ]
