# Generated by Django 3.0.6 on 2020-06-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200624_1541'),
        ('purchases', '0003_auto_20200624_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStock',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stocks.Stock')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase')),
            ],
            bases=('stocks.stock',),
        ),
    ]
