# Generated by Django 3.0.6 on 2020-06-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockorder'),
        ('purchases', '0004_purchasestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasestock',
            name='stock_ptr',
        ),
        migrations.AddField(
            model_name='purchasestock',
            name='stockorder_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stocks.StockOrder'),
            preserve_default=False,
        ),
    ]
