# Generated by Django 3.0.6 on 2020-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20200624_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expect_received_date',
            field=models.DateField(help_text='วันที่คาดกว่าจะได้'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='expect_sending_date',
            field=models.DateField(help_text='วันที่คาดว่าจะส่งของ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(help_text='วันสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='received_date',
            field=models.DateField(help_text='วันที่รับของ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='request_date',
            field=models.DateField(auto_now=True, help_text='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sending_date',
            field=models.DateField(help_text='วันที่ส่งของ'),
        ),
    ]
