version: '3'
services:
  web:
    container_name: web
    build:
      context: services-web
      dockerfile: Dockerfile
    env_file:
      - .env.local
    command: bash -c "chmod +x entrypoints/local.sh && entrypoints/local.sh"
    volumes:
      - ./services-web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
