version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./service-nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./service-web/erp/static:/static
      - ./service-web/erp/media:/media
    depends_on:
      - web

  web:
    container_name: web
    build:
      context: services-web
      dockerfile: Dockerfile
    env_file:
      - .env.local
    command: bash -c "chmod +x entrypoints/local.sh && entrypoints/local.sh"
    volumes:
      - ./services-web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./services-web:/config
    ports:
      - 8443:8443
    restart: unless-stopped

volumes:
  db-data:
